### ISSUE TITLE
license for reuse

### ISSUE THREAD

**Issue by leomiquelutti** [banesullivan/banesullivan#4]
Hi Bane, 

I will deliver a class on how to use PyVista to my grad students, and I would like to use the content you made available on your personal website as the support material on the Google Colab file. 

Could I use it, please, surely giving you the proper credit?

**Comment by banesullivan** [comment]
Hey, thanks for checking. That is absolutely okay!

I didn't realize I forgot to add a license here. I'll update this with a standard MIT license and note it as such on my website

**Comment by banesullivan** [comment]
See https://github.com/banesullivan/mywebsite/blob/master/README.md#license

and https://github.com/banesullivan/mywebsite/blob/master/LICENSE
